# Generated by Django 4.1 on 2022-09-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_historicaluser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
