# Generated by Django 4.1 on 2022-09-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["dept_name"]},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["dept_name"], name="candidates__dept_na_3cd64e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["contact"], name="candidates__contact_404f08_idx"
            ),
        ),
    ]
